var productos = [
    {
        id:1,
        nombre: "Hidro lavadora Small",
        precio: "$ 5.799",
        foto: "imagenes/productos/hidroSmall.jpg",
        descripcion: "Con sistema de apagado automático, que produce la detención del motor, cuando se deja de presionar el gatillo. Limpia de forma más rápida y efectiva con el mayor ahorro de agua. La más Eficiente del Mercado.Ideal para limpiar vehículos, bicicletas, máquinas, embarcaciones, piletas, patios y paredes.",
        ubicacionDepo: "Ballester",
        stock: 77,
        categoria: "",
    },		
    {		
        id:2,
        nombre: "Hidro lavadora Medium",
        precio: "$ 7.499",
        foto: "imagenes/productos/hidroMedium.jpg",
        descripcion: "Hidrolavadora de alta presión.Con sistema AutoStop, que produce la detención automática del motor, cuando se deja de presionar el gatillo. Limpia de forma más rápida y efectiva con el mayor ahorro de agua. Ideal para limpiar vehículos, máquinas, embarcaciones, piletas, paredes.",
        ubicacionDepo: "Ballester",
        stock: 100,
        categoria: "",
    },		
    {
        id:3,
        nombre: "Hidro lavadora Big",
        precio: "$ 14.723",
        foto: "imagenes/productos/hidroBig.jpg",
        descripcion: "Modelo LA-1500.Potencia Máxima: 1400 Watts.Capacidad del Tacho de acero inoxidable: 15 Lts.Funcion soplador.Equipado con filtro de espuma.longitud de la manguera 1.5 mts. Voltaje 220V",
        ubicacionDepo: "Ballester",
        stock: 50,
        categoria: "",
    },		
    {		
        id:4,
        nombre: "Pulidora Hogar",
        precio: "$ 6.559",
        foto: "imagenes/productos/pulidoraHogar.jpg",
        descripcion: "La pulidora angular TC-PO 1100/2E de Einhell es la pulidora y lijadora profesional potente, robusta y de fácil manejo para el aficionado al bricolaje ambicioso, ideal para el pulido de superficies lacadas, así como lijado de madera, plástico y metal. ",
        ubicacionDepo: "Ballester",
        stock: 10,
        categoria: "",
    },		
    {
        id:5,
        nombre: "Pulidora Pro",
        precio: "$ 12.559",
        foto: "imagenes/productos/pulidoraPro.jpg",
        descripcion: "El número de revoluciones de las piezas adicionales de pulido y lijado se puede adaptar de forma óptima a la base correspondiente a mecanizar gracias a la unidad electrónica de precisión para regular el número de revoluciones. Con el práctico de bloqueo del husillo, el husillo se puede bloquear sin herramientas y por consiguiente cambiar el disco abrasivo en el autopulido de forma rápida y sencilla.",
        ubicacionDepo: "Ballester",
        stock: 64,
        categoria: "",
    },		
    {	
        id:6,
        nombre: "Paños microfibra 40x40",
        precio: "$ 450",
        foto: "imagenes/productos/paños40x40.jpg",
        descripcion: "Esta microfibra de gran gramaje es la opcion ideal para el sacado. Seca y no deja betas muy facilmente.",
        ubicacionDepo: "Ballester",
        stock: 45,
        categoria: "",
    },		
    {
        id:7,
        nombre: "Paños microfibra 60x40",
        precio: "$ 550",
        foto: "imagenes/productos/paños60x40.jpg",
        ubicacionDepo: "Ballester",
        descripcion: "Alta densidad, gran capacidad de absorción. No raya, no deja marcas, ni pelusas",
        stock: 88,
        categoria: "",
    },		
    {
        id:8,
        nombre: "Shampoo 500cc",
        precio: "$ 580",
        foto: "imagenes/productos/shampoo500cc.jpg",
        descripcion: "Su fórmula con PH Neutro está especialmente diseñada para no quitar las capas de cera ya existente a la vez que añade una nueva, dejando su vehículo limpio y encerado lavado tras lavado.",
        ubicacionDepo: "Ballester",
        stock: 72,
        categoria: "",
    },		
    {
        id:9,
        nombre: "Shampoo 1lt",
        precio: "$ 1.050",
        foto: "imagenes/productos/shampoo1lt.jpg",
        descripcion: "Su espuma densa y firme desprende y encapsula la suciedad permitiendo una limpieza sin rayones, a la vez que ahorra tiempo y agua.",
        ubicacionDepo: "Ballester",
        stock: 100,
        categoria: "",
    },		
    {
        id:10,
        nombre: "Cera 500cc",
        precio: "$ 400",
        foto: "imagenes/productos/cera500cc.jpg",
        descripcion: "Su fórmula exclusiva que combina ceras naturales, sintéticas y siliconas otorgan un brillo intenso y un capa protectora sobra la pintura de su automóvil",
        ubicacionDepo: "Ballester",
        stock: 100,
        categoria: "",
    },		
    {
        id:11,
        nombre: "Cera 1lt",
        precio: "$ 780",
        foto: "imagenes/productos/cera1lt.jpg",
        descripcion: "Secado rápido con brillo instantáneo lormando una película dura y autobrillante sin necesidad de lustrar y resaltando el color natural tanto",
        ubicacionDepo: "Ballester",
        stock: 100,
        categoria: "",
    },
    {
        id:12,
        nombre: "Silicona 300cc",
        precio: "$ 640",
        foto: "imagenes/productos/silicona300cc.jpg",
        descripcion: "",
        ubicacionDepo: "Ballester",
        stock: 100,
        categoria: "",
    },{
        id:13,
        nombre: "Pulidor 100cc",
        precio: "$ 260",
        foto: "imagenes/productos/pulidor100cc.jpg",
        descripcion: "Restaura el color y la claridad de pinturas abusadas y abandonadas. Su revolucionaria formula con nueva tecnología de microabrasivos corta de manera rápida sin rayar la pintura. Remueve fácil y rápidamente manchas, oxidacion, rayones o manchas de gota seca de manera permanente. Es seguro de usar en cualquier tipo de pintura.",
        ubicacionDepo: "Ballester",
        stock: 21,
        categoria: "",
    },
    {
        id:14,
        nombre: "Esponja Sintética",
        precio: "$ 299",
        foto: "imagenes/productos/esponja.jpg",
        descripcion: "Esponja de lavado auto lana sintetica mullida. Alta densidad y calidad. Tamaño 28x20 CMS",
        ubicacionDepo: "Ballester",
        stock: 9,
        categoria: "",
    },
    

]